version: '3.8'
services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    environment:
      ROLE_ARN: ${ROLE_ARN}
      MFA_SERIAL: ${MFA_SERIAL}
    command: /bin/sh
    tty: true
    volumes:
      - .:/code

