---
- hosts: all
  tasks:
    - debug:
        var: lookup("env", "TESTVAR")

    - name: "Get timestamp from the system"
      shell: "date +%Y-%m-%d-%H-%M-%S"
      register: tstamp

    - name: "Assume Role"
      sts_assume_role:
        role_arn: '{{ lookup("env", "ROLE_ARN") }}'
        mfa_serial_number: '{{ lookup("env", "MFA_SERIAL") }}'
        mfa_token: "{{ mfa_token }}"
        role_session_name: "ansible-session"
        region: "ap-northeast-1"
      register: assumed_role
      changed_when: False

    - name: "RDS instance for testing"
      community.aws.rds_instance_info:
        region: ap-northeast-1
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
      register: instances

    - name: "Output to json"
      local_action:
        module: lineinfile
        dest: "{{ tstamp.stdout + '.json' }}"
        line: "{{ instances | to_nice_json(indent=2) }}"
        create: yes

    - name: "PUT S3"
      amazon.aws.aws_s3:
        region: ap-northeast-1
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"

        bucket: "{{ bucket }}"
        object: "{{ tstamp.stdout + '.json' }}"
        src: "{{ tstamp.stdout + '.json' }}"
        mode: put

    # - name: instance for testing
    #   community.aws.ec2_instance_info:
    #     region: ap-northeast-1
    #     profile: aoz-cli-dev
    #     filters:
    #       tag:CmBillingGroup: grid-line-detection-api
    #   register: instances
    # - debug: msg="{{ instances }}"
